### ISSUE TITLE
로고 건의사항

### ISSUE THREAD

**Issue by daniel2231** [SKKU-SWForum/IssueTracker#2]
![image](https://user-images.githubusercontent.com/39212398/116216236-60b59780-a783-11eb-9af2-c020729e3b76.png)

![image](https://user-images.githubusercontent.com/39212398/116216049-28ae5480-a783-11eb-9dd1-a36ae1e1d944.png)

![image](https://user-images.githubusercontent.com/39212398/116216061-2ba94500-a783-11eb-8c29-27b75017a120.png)

![image](https://user-images.githubusercontent.com/39212398/116216069-2ea43580-a783-11eb-9fdb-a1535a011729.png)

구인구직글에 로고 관련 내용이 있어서 (쉴겸) 로고를 조금 만들어봤습니다. 예쁘진 않지만 실력있는 디자이너가 오기 전까지는 써도 될것 같은데 의견 부탁 드립니다!

**Comment by raven724** [comment]
로고 디자인해주신 것 잘 봤습니다. 감사드립니다. 다 좋은데 어떤 걸 선택해야할지 몰라서 온카톡방에 투표를 올려달라고 방장님께 요청드리려 합니다. 괜찮으신가요? @daniel2231

**Comment by daniel2231** [comment]
넵 저는 상관 없습니다! @raven724

**Comment by raven724** [comment]
네 감사합니다.

**Comment by gwonhong** [comment]
1번 로고는 마음에 드는데 밑에 텍스트 부분을 제가 원하는대로 조오금 고쳐봤습니다. 해당 수정본 여기 코멘트로 올려도 괜찮을까요? @daniel2231

**Comment by daniel2231** [comment]
넵 올려주시면 됩니다! @rgb-spectrum

**Comment by gwonhong** [comment]
![1619632333808](https://user-images.githubusercontent.com/75533669/116503393-ec990200-a8f0-11eb-8da7-e97d75d543c7.png)
ㅎㅎ올려봤습니다~!

**Comment by daniel2231** [comment]
더 나은것 같네요! 만약 1번이 선정되면 저걸로 해도 될 것 같습니다.

**Comment by raven724** [comment]
![image](https://user-images.githubusercontent.com/39472872/116877831-6adf0680-ac59-11eb-99ab-01ae332ad367.png)
로고 투표 결과입니다.
투표 결과 2번이 채택되었습니다. 빠른 시간 안에 적용하겠습니다.

**Comment by daniel2231** [comment]
웹사이트에는 제가 적용시켜보겠습니다.

**Comment by raven724** [comment]
@daniel2231 늘 감사드립니다.

**Comment by raven724** [comment]
로고 반영되었습니다. 이슈를 정리합니다.
